# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: myService # NOTE: update this with your service name

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1

package:
  individually: true

functions:
  hello:
    handler: AwsDotnetCsharp::AwsDotnetCsharp.Handler::HelloWorld
    package:
      artifact: bin/release/net6.0/hello.zip

    events:
      - http:
          path: hello
          method: get
  getquerystring:
    handler: AwsDotnetCsharp::AwsDotnetCsharp.Handler::GetQuerystring

    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: getquerystring
          method: get
